import 'package:flutter/widgets.dart';
import 'package:provider/provider.dart';
import 'providers/locale_provider.dart';

const Map<String, Map<String, String>> _t = {
  'en': {
    'app_title': 'SmartNav',
    'patient_menu': 'Patient Menu',
    'remote_control': 'Remote Control',
    'manual_control': 'Manual Control',
    'joystick_control': 'Joystick Control',
    'voice_control': 'Voice Control',
    'forward': 'Forward',
    'left': 'Left',
    'right': 'Right',
    'backward': 'Backward',
    'stop': 'Stop',
    'bluetooth_settings': 'Bluetooth settings',
    'emergency_stop_sent': 'Emergency stop sent',
    'wifi_disconnected': 'Wi-Fi disconnected',
    'connecting': 'Connecting...',
    'connecting_to_wheelchair': 'Connecting to SmartNav',
    'connected_to_wheelchair': 'Connected to SmartNav',
    'add_your_voice': 'Add Your Voice',
    'connection_settings': 'Connection Settings',
    'go_to': 'Go to',
    'kitchen': 'Kitchen',
    'bedroom': 'Bedroom',
    'living_room': 'Living Room',
    'streaming_motion': 'Streaming motion via joystick',
    'bluetooth_connected': 'Bluetooth connected',
    'connect_bluetooth':
        'Connect to SmartNav over Bluetooth to enable joystick control',
    'not_connected': 'Not connected',
    'settings': 'Settings',
    'wheelchair_configuration': 'SmartNav Configuration',
    'speed_control': 'Speed Control',
    'sensitivity': 'Sensitivity',
    'user_preferences': 'User Preferences',
    'emergency_contacts': 'Emergency Contacts',
    'voice_commands': 'Voice Commands',
    'system': 'System',
    'device_info': 'Device Info',
    'bluetooth_control': 'Bluetooth Control',
    'connection_status': 'Connection Status',
    'battery': 'Battery',
    'battery_level': 'Battery Level: 75%',
    'battery_estimate': 'Estimated 4 hours remaining',
    'close': 'Close',
    'health_status': 'Health Status',
    'location': 'Location',
    'logout': 'Logout',
  },
  'hi': {
    'app_title': 'स्मार्ट नेव', // Smart Nav transliteration
    'patient_menu': 'रोगी मेनू',
    'remote_control': 'रिमोट नियंत्रण',
    'manual_control': 'मैनुअल नियंत्रण',
    'joystick_control': 'जॉयस्टिक नियंत्रण',
    'voice_control': 'वॉयस नियंत्रण',
    'forward': 'आगे',
    'left': 'बायाँ',
    'right': 'दाएँ',
    'backward': 'पीछे',
    'stop': 'रोकें',
    'bluetooth_settings': 'ब्लूटूथ सेटिंग्स',
    'emergency_stop_sent': 'इमरजेंसी स्टॉप भेजा गया',
    'go_to': 'जाओ',
    'kitchen': 'रसोई',
    'bedroom': 'शयनकक्ष',
    'living_room': 'बैठक कक्ष',
    'streaming_motion': 'जॉयस्टिक के माध्यम से मूवमेंट भेजा जा रहा है',
    'bluetooth_connected': 'ब्लूटूथ जुड़ा हुआ',
    'connect_bluetooth':
        'जॉयस्टिक नियंत्रण सक्षम करने के लिए SmartNav से ब्लूटूथ कनेक्ट करें',
    'not_connected': 'अवचार्य नहीं',
    'settings': 'सेटिंग्स',
    'wheelchair_configuration': 'SmartNav कॉन्फिगरेशन',
    'speed_control': 'गति नियंत्रण',
    'sensitivity': 'संवेदनशीलता',
    'user_preferences': 'उपयोगकर्ता वरीयताएँ',
    'emergency_contacts': 'आपातकालीन संपर्क',
    'voice_commands': 'वॉइस कमांड',
    'system': 'सिस्टम',
    'device_info': 'डिवाइस जानकारी',
    'bluetooth_control': 'ब्लूटूथ नियंत्रण',
    'connection_status': 'कनेक्शन स्थिति',
    'battery': 'बैटरी',
    'battery_level': 'बैटरी स्तर: 75%',
    'battery_estimate': 'अनुमानित 4 घंटे शेष',
    'close': 'बंद करें',
    'health_status': 'स्वास्थ्य स्थिति',
    'location': 'स्थान',
    'logout': 'लॉगआउट',
  },
  'mr': {
    'app_title': 'स्मार्ट नेव',
    'patient_menu': 'रुग्ण मेनू',
    'remote_control': 'रिमोट नियंत्रण',
    'manual_control': 'मन्युअल नियंत्रण',
    'joystick_control': 'जॉयस्टिक नियंत्रण',
    'voice_control': 'वॉइस नियंत्रण',
    'forward': 'पुढे',
    'left': 'डाव्या',
    'right': 'उजव्या',
    'backward': 'मागे',
    'stop': 'थांबवा',
    'bluetooth_settings': 'ब्लूटूथ सेटिंग्ज',
    'emergency_stop_sent': 'आपत्कालीन थांबवणे पाठवले',
    'go_to': 'जा येथे',
    'kitchen': 'स्वयंपाकघर',
    'bedroom': 'बेडरूम',
    'living_room': 'लिव्हिंग रूम',
    'streaming_motion': 'जॉयस्टिकद्वारे हालचाल पाठविली जात आहे',
    'bluetooth_connected': 'ब्लूटूथ जोडले',
    'connect_bluetooth':
        'जॉयस्टिक नियंत्रण सक्षम करण्यासाठी SmartNav शी ब्लूटूथ कनेक्ट करा',
    'not_connected': 'कनेक्ट नाही',
    'settings': 'सेटिंग्ज',
    'wheelchair_configuration': 'SmartNav कॉन्फिगरेशन',
    'speed_control': 'गती नियंत्रण',
    'sensitivity': 'संवेदनशीलता',
    'user_preferences': 'वापरकर्ता प्राधान्ये',
    'emergency_contacts': 'आपत्कालीन संपर्क',
    'voice_commands': 'व्हॉइस कमांड',
    'system': 'सिस्टम',
    'device_info': 'डिवाइस माहिती',
    'bluetooth_control': 'ब्लूटूथ नियंत्रण',
    'connection_status': 'कनेक्शन स्थिती',
    'battery': 'बॅटरी',
    'battery_level': 'बॅटरी पातळी: 75%',
    'battery_estimate': 'अंदाजे 4 तास शिल्लक',
    'close': 'बंद करा',
    'health_status': 'आरोग्य स्थिती',
    'location': 'स्थान',
    'logout': 'लॉगआउट',
  },
};

String tr(BuildContext context, String key) {
  final provider = context.watch<LocaleProvider>();
  final code = provider.locale;
  return _t[code]?[key] ?? _t['en']![key] ?? key;
}
