// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCow7A8gcGkx9x0DIu9FWmOKOjhs1tlGgU',
    appId: '1:561119263095:web:c529115c696cf2cf20c972',
    messagingSenderId: '561119263095',
    projectId: 'smartnav-14012',
    authDomain: 'smartnav-14012.firebaseapp.com',
    storageBucket: 'smartnav-14012.firebasestorage.app',
    measurementId: 'G-VYYT096M0L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQjTppustXZNViBOXRN-luKkryKdZOKAg',
    appId: '1:561119263095:android:5d44085a40c461b620c972',
    messagingSenderId: '561119263095',
    projectId: 'smartnav-14012',
    storageBucket: 'smartnav-14012.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqewnp-DujpRj3BehtYwk3tLZMExmm97A',
    appId: '1:561119263095:ios:69ce26d87e514bc520c972',
    messagingSenderId: '561119263095',
    projectId: 'smartnav-14012',
    storageBucket: 'smartnav-14012.firebasestorage.app',
    iosBundleId: 'com.example.smartWheelchairApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqewnp-DujpRj3BehtYwk3tLZMExmm97A',
    appId: '1:561119263095:ios:69ce26d87e514bc520c972',
    messagingSenderId: '561119263095',
    projectId: 'smartnav-14012',
    storageBucket: 'smartnav-14012.firebasestorage.app',
    iosBundleId: 'com.example.smartWheelchairApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCow7A8gcGkx9x0DIu9FWmOKOjhs1tlGgU',
    appId: '1:561119263095:web:a5c5714c7d3083eb20c972',
    messagingSenderId: '561119263095',
    projectId: 'smartnav-14012',
    authDomain: 'smartnav-14012.firebaseapp.com',
    storageBucket: 'smartnav-14012.firebasestorage.app',
    measurementId: 'G-XHEXH2NYYW',
  );
}
